In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn import svm
import matplotlib.pyplot as plt

In [2]:
BASEDIR = os.getcwd()
FILENAME = 'dataset.csv'
FILEPATH = os.path.join(BASEDIR, FILENAME)

In [3]:
df = pd.read_csv(FILEPATH)
df.head(5)

rowSize  colSize  numberOfSolutions  numberOfOnes  solutionsPerPath  \
0       13       11                  3            30          0.020979   
1       13       21                 24            56          0.087912   
2       12       16                  9            41          0.046875   
3        8        9                  9            19          0.125000   
4        8        9                  4            18          0.055556   

   difficultyLevel  
0                2  
1                4  
2                3  
3                2  
4                2

In [4]:
X = df.drop(['difficultyLevel'], axis=1)
X.head()

rowSize  colSize  numberOfOnes
0       13       11            30
1       13       21            56
2       12       16            41
3        8        9            19
4        8        9            18

In [5]:
y = df['difficultyLevel']
y.head()

0    2
1    4
2    3
3    2
4    2
Name: difficultyLevel, dtype: int64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=49, shuffle=True)

In [7]:
LR = LogisticRegression(solver='newton-cg', random_state=49)

In [8]:
model = LR.fit(X_train, y_train)

In [9]:
y_pred = model.predict(X_test)
y_pred

array([3, 2, 4, 1, 1, 3, 3, 3, 4, 4, 2, 4, 3, 4, 3, 3, 3, 1, 2, 3, 1, 2,
       3, 3, 5, 4, 1, 3, 3, 3, 4, 1, 5, 3, 1, 2, 2, 5, 2, 2, 3, 4, 3, 2,
       5, 3, 4, 3, 4, 3, 3, 4, 3, 3, 5, 2, 4, 3, 3, 4, 3, 2, 3, 5, 5, 3,
       3, 2, 2, 1], dtype=int64)

In [10]:
accuracy_score(y_pred, y_test)

0.7142857142857143

In [11]:
SVM = svm.SVC(kernel='linear')

In [12]:
model = SVM.fit(X_train, y_train)

In [13]:
y_pred = model.predict(X_test)
y_pred

array([4, 2, 4, 1, 1, 3, 3, 3, 4, 4, 2, 4, 3, 4, 3, 3, 4, 1, 2, 3, 1, 2,
       3, 3, 5, 4, 1, 3, 3, 3, 4, 1, 5, 3, 1, 2, 2, 5, 2, 2, 3, 4, 3, 2,
       5, 3, 4, 3, 4, 3, 3, 4, 3, 3, 5, 2, 4, 3, 3, 4, 3, 3, 4, 5, 4, 3,
       3, 2, 2, 1], dtype=int64)

In [14]:
accuracy_score(y_pred, y_test)

0.7428571428571429

In [15]:
SVM = svm.SVC(kernel='poly')

In [16]:
model = SVM.fit(X_train, y_train)

In [17]:
y_pred = model.predict(X_test)
y_pred

array([4, 2, 4, 1, 1, 3, 3, 3, 4, 4, 2, 4, 3, 4, 3, 3, 4, 1, 2, 3, 1, 2,
       3, 3, 5, 4, 1, 3, 3, 3, 4, 1, 5, 3, 1, 2, 2, 5, 2, 2, 3, 4, 3, 2,
       5, 3, 4, 3, 4, 3, 3, 4, 3, 3, 4, 2, 4, 3, 3, 4, 3, 2, 4, 5, 4, 3,
       3, 2, 2, 1], dtype=int64)

In [18]:
accuracy_score(y_pred, y_test)

0.7714285714285715

In [19]:
SVM = svm.SVC(kernel='poly', degree=3)

In [20]:
model = SVM.fit(X_train, y_train)

In [21]:
y_pred = model.predict(X_test)
y_pred

array([4, 2, 4, 1, 1, 3, 3, 3, 4, 4, 2, 4, 3, 4, 3, 3, 4, 1, 2, 3, 1, 2,
       3, 3, 5, 4, 1, 3, 3, 3, 4, 1, 5, 3, 1, 2, 2, 5, 2, 2, 3, 4, 3, 2,
       5, 3, 4, 3, 4, 3, 3, 4, 3, 3, 4, 2, 4, 3, 3, 4, 3, 2, 4, 5, 4, 3,
       3, 2, 2, 1], dtype=int64)

In [22]:
accuracy_score(y_pred, y_test)

0.7714285714285715

In [23]:
SVM = svm.SVC(kernel='rbf')

In [24]:
model = SVM.fit(X_train, y_train)

In [25]:
y_pred = model.predict(X_test)
y_pred

array([3, 2, 4, 1, 1, 3, 3, 3, 5, 4, 2, 4, 3, 4, 3, 3, 3, 1, 2, 3, 1, 2,
       3, 3, 5, 3, 1, 3, 3, 3, 4, 1, 4, 3, 1, 2, 2, 4, 2, 2, 3, 4, 3, 2,
       5, 3, 4, 3, 4, 3, 3, 4, 3, 3, 4, 2, 4, 3, 3, 4, 3, 2, 3, 4, 4, 3,
       3, 2, 2, 1], dtype=int64)

In [26]:
accuracy_score(y_pred, y_test)

0.6714285714285714