In [7]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn import svm
import matplotlib.pyplot as plt

In [8]:
BASEDIR = os.getcwd()
FILENAME = 'dataset.csv'
FILEPATH = os.path.join(BASEDIR, FILENAME)

In [9]:
df = pd.read_csv(FILEPATH)
df.head(5)

mazeSize  wallDensity  branchingFactor  solutionDistortions  MSTCost  \
0         5           64                4                   12       24   
1         9           75               20                   30       50   
2        13           78               40                   42       90   
3         5           64                5                   16       24   
4         8           76               19                   26       63   

   difficultyLevel  
0                1  
1                1  
2                2  
3                1  
4                1

In [10]:
X = df.drop(['difficultyLevel'], axis=1)
X.head()

mazeSize  wallDensity  branchingFactor  solutionDistortions  MSTCost
0         5           64                4                   12       24
1         9           75               20                   30       50
2        13           78               40                   42       90
3         5           64                5                   16       24
4         8           76               19                   26       63

In [11]:
y = df['difficultyLevel']
y.head()

0    1
1    1
2    2
3    1
4    1
Name: difficultyLevel, dtype: int64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=49, shuffle=True)

In [13]:
LR = LogisticRegression(solver='newton-cg', random_state=49)

In [14]:
model = LR.fit(X_train, y_train)

In [15]:
y_pred = model.predict(X_test)
y_pred

array([2, 3, 3, 3, 3], dtype=int64)

In [16]:
accuracy_score(y_pred, y_test)

0.4

In [17]:
SVM = svm.SVC(kernel='linear')

In [18]:
model = SVM.fit(X_train, y_train)

In [19]:
y_pred = model.predict(X_test)
y_pred

array([2, 3, 4, 3, 3], dtype=int64)

In [20]:
accuracy_score(y_pred, y_test)

0.4

In [21]:
SVM = svm.SVC(kernel='poly')

In [22]:
model = SVM.fit(X_train, y_train)

In [23]:
y_pred = model.predict(X_test)
y_pred

array([2, 2, 4, 2, 3], dtype=int64)

In [24]:
accuracy_score(y_pred, y_test)

0.4

In [25]:
SVM = svm.SVC(kernel='poly', degree=3)

In [26]:
model = SVM.fit(X_train, y_train)

In [27]:
y_pred = model.predict(X_test)
y_pred

array([2, 2, 4, 2, 3], dtype=int64)

In [28]:
accuracy_score(y_pred, y_test)

0.4

In [29]:
SVM = svm.SVC(kernel='rbf')

In [30]:
model = SVM.fit(X_train, y_train)

In [31]:
y_pred = model.predict(X_test)
y_pred

array([2, 2, 3, 2, 3], dtype=int64)

In [32]:
accuracy_score(y_pred, y_test)

0.4